services: 
  app:
    build: .
    container_name: Test_1_FastAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes: 
      - .:/app
    
  db:
    image: postgres:14
    container_name: postgres_Db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data  
  
volumes:
  pg_data: